 
-- drop table pub_clog 
-- alter pub_clog add (state varchar(50) NULL); 
create table pub_clog (
pk_log char(20) NOT NULL,
code varchar(50) NULL,
name varchar(50) NULL,
src_sys varchar(50) default '~' NULL,
src_id varchar(50) default '~' NULL,
res_direct int NULL,
logdate char(19) NULL,
ip varchar(50) default '~' NULL,
url varchar(1000) NULL,
action varchar(250) default '~' NULL,
sessionid varchar(250) default '~' NULL,
token varchar(3800) default '~' NULL,
userid varchar(50) default '~' NULL,
cookes text NULL,
request text NULL,
response text NULL,
message text NULL,
thwmsg text NULL,

  -- response     CLOB,
  -- request      CLOB,
  -- thwmsg       CLOB,
  
state varchar(50) NULL,
restcode varchar(50) NULL,
startime varchar(101) default '~' NULL,
endtime varchar(101) default '~' NULL,
runtime varchar(101) default '~' NULL,
tenantid varchar(250) default '~' NULL,
tenantcode varchar(250) default '~' NULL,
referer varchar(250) default '~' NULL,
localaddr varchar(50) default '~' NULL,
clientip  varchar(50) default '~' NULL,
datatype varchar(101) default '~' NULL,
billdate char(19) NULL,
enable char(1) NULL,
memo varchar(2500) default '~' NULL,
creator varchar(20) default '~' NULL,
creationtime char(19) NULL,
modifier varchar(20) default '~' NULL,
modifiedtime char(19) NULL,
pk_group varchar(20) default '~' NULL,
pk_org varchar(20) default '~' NULL,
pk_org_v varchar(20) default '~' NULL,
def01 varchar(1000) default '~' NULL,
def02 varchar(1000) default '~' NULL,
def03 varchar(1000) default '~' NULL,
def04 varchar(1000) default '~' NULL,
def05 varchar(1000) default '~' NULL,
def06 varchar(101) default '~' NULL,
def07 varchar(101) default '~' NULL,
def08 varchar(101) default '~' NULL,
def09 varchar(101) default '~' NULL,
def10 varchar(101) default '~' NULL,
def11 varchar(101) default '~' NULL,
def12 varchar(101) default '~' NULL,
def13 varchar(101) default '~' NULL,
def14 varchar(101) default '~' NULL,
def15 varchar(101) default '~' NULL,
def16 varchar(101) default '~' NULL,
def17 varchar(101) default '~' NULL,
def18 varchar(101) default '~' NULL,
def19 varchar(101) default '~' NULL,
def20 varchar(101) default '~' NULL,
CONSTRAINT PK_PUB_CLOG PRIMARY KEY (pk_log),
ts char(19) NULL,
dr smallint default 0 
)



